# Ejercicios {#Ejercicios}

En esta sección, se presenta un conjunto de ejercicios en R los cuales se iran presentando/asignando de manera periódica a lo largo del desarrollo del presente curso. Estos, están orientados a afianzar los conocimientos adquiridos en el proceso de aprendizaje y a fomentar su discusión en algunas de las sesiones virtuales del curso.

## Trabajo 1


1. ¿Qué regla aplica R para evaluar/desarrollar la operación aritmética compuesta `(6/2*(2+1 + 2^3) + 24/(2*3 + 0^3) + 3)/8`? Explicar, paso a paso y mediante varias líneas de comando, ¿cómo este lenguaje genera el resultado de la anterior operación?

2. Escriba el número pi haciendo uso de la constante integrada `pi`, guarde su valor dentro de una variable llamada `longitud circunferencia vs radio` e imprima su resultado. <br> 
_**Nota: el nombre de la variable debe respetar los espacios existentes entre las diferentes palabras.**_  

3. Escribra un dato de tipo lógico, almacene/guarde su contenido en una variable llamada `Var%_1` e imprima su resultado. ¿Qué pasó al imprimir el resultado en R?, ¿Cómo arreglaría el problema generado para que imprima el resultado de manera correcta?

4. Crear dos vectores en R con los números de 5 en 5: uno  iniciando en 5 y terminando en 100 y el otro iniciando en 100 y terminando en 5. Es decir, `c(5, 10, 15, 20, ... 100)` y `c(100, 95, 90, 85, ... 5)`.

5. Cree en R, a partir de las funciones vistas para generar vectores de manera rápida (`:, seq() o rep()`), el siguiente vector c("a", "b", "b", "c", "c", "c", "d", "d", "d", "d").

6. Cree la variable `var_1` y asigne a esta los elementos del vector `c(1:10)`; luego cree la variable `var_2` y asigne los elementos contenidos en el vector `c(1, 0)`. Una vez se hayan creado los anteriores dos vectores, cree una nueva variable `Rta` y almacene allí la división entre los vectores `var_1` y `var_2`. ¿Qué regla aplica R para realizar esta operación dado que los vectores son de diferente longitud? ¿Qué le llama la atención de los tipos de datos que genera esta división? ¿Qué explicación podría dar a los datos "raros" que esta operación genera?

7. Cree la variable `x` y asigne a esta los elementos del vector `c(10, 15, 20 , '30')`; luego cree la variable `y` y asigne los elementos contenidos en el vector `c(2, 5, '2', 10)`.  Una vez se hayan creado los anteriores dos vectores, cree una nueva variable `z` y almacene allí la multiplicación entre los vectores `x` e `y`. ¿Por qué se genera un error al realizar la multiplicación entre los vectores `x` e `y`?, ¿qué regla está aplicando R a los elementos que conforman los vectores `x` e `y` antes de realizar la multiplicación? ¿Cómo solucionaria el problema generado por R para que se pueda implementar la multiplicación deseada? <br>
_**Nota: Copie el contenido de los vectores `x` e `y` directamente desde el ejercicio; es decir, no los ingrese manualmente a través del teclado.**_  

8. Cree en R un vector con los números del 1 al 100 y almacene el resultado en una variable llamada `m`. Haciendo uso de operadores relacionales, genere un vector lógico en donde TRUE contenga las posiciones de los elementos menores o iguales a 10 (`<= 10`) que hacen parte del vector `m`.

9. Cree la variable `Números` y asigne a esta los elementos del vector `c('uno', 'tres', 'uno ', 'cuatro', ' uno', 'cinco', 'uno')`. Haciendo uso de operadores lógicos de tipo relacional, cree una variable llamada `Resultado` y almacene allí un vector lógico con las posiciones en donde la variable `Números` es **igual** a la palabra `uno`, imprima los resultados contenidos en la variable `Resultado`. ¿Por qué algunos elementos del vector contenido en la variable `Números`, que tienen la palabra `uno`, no aparecen como `TRUE` en el vector lógico contenido en la variable `Resultado`? Realice los ajustes que considere pertinentes al vector `Números` para que la totalidad de los elementos que contienen la palabra `uno` aparezcan como `TRUE` en el vector lógico contenido en la variable `Resultado`.<br>
_**Nota: Copie el contenido del vector `Números` directamente desde el ejercicio; es decir, no los ingrese manualmente a través del teclado.**_  

10. Cree la variable `var_1` y asigne a esta los elementos del vector `seq(-5, 5, 1)`; luego cree la variable `var_2` y asigne los elementos contenidos en el vector `c(-5, 1, 2, -5, 3, 1, 0, -4, -5, 3, 1, -5)`. Implemente en R una expresión lógica que contenga las posiciones en donde los elementos de la variable `var_1` son menores o iguales a cero **y** los elementos del vector `var_2` son iguales a `-5`, `2` o `-4`.<br>
_**Nota: Investigue en la web el operador `%in%` en R y úselo si lo considera útil para desarrollar este ejercicio**_

11. Cree la variable `Serie` y asigne a esta los números del 1 al 99 de dos en 2 (`1, 3, 5, 7, ... , 99`). Seleccione, haciendo uso del operador `[ ]` (corchetes), los elementos múltiplos de 5 contenidos en el vector `Serie` y almacene el resultado en una variable llamada `Multiplo5`. Imprima los resultados contenidos en la variable `Multiplo5`. ¿Por qué la variable `Multiplo5` no genera un conflicto en R a pesar de que esta contiene un número en su nombre?

12. Cree la variable `Var` en R y almacene en ella las primeras 5 letras del abecedario romano a partir de la constante integrada `LETTERS`. Cree, a partir de los elementos almacenados en la variable `Var`, una variable llamada `Rep_Var` con cada uno de los elementos contenidos en la variable `Var` de manera duplicada; es decir, `"A" "A" "B" "B" "C" "C" "D" "D" "E" "E"`. Imprima los resultados de la variable `Rep_Var`.<br>
_**Nota: Los elementos de la variable `Var` no pueden ser ingresados desde el teclado; estos deben ser extraidos (un subconjunto) a partir del uso de la constante integrada `LETTERS`.**_ 

13. Cree la variable `Nueva` y asigne a esta los elementos del vector `c(11, 20, 15, 10)`; cree la variable `Nombres` y asigne a esta los elementos del vector `c('xyz', 'c%2', 'mno', 'for')`. Asigne a los elementos de la variable `Nueva` los nombres contenidos en la variable `Nombres` e imprima los resultados. Seleccione los elementos del vector contenido en la variable `Nueva` cuyos nombres son `xyz` y `for`. ¿Por qué cree que R no genera un error en los nombres de los elementos contenidos en el vector `Nombres` a pesar de que dos de ellos usan caracteres especiales del lenguaje R o palabras reservadas (`c%2` y `for`)? 

## Trabajo 2

1. Cree en R una matriz de 5 `filas` y 4 `columnas`, ingrese los datos por filas a través de un vector que contenga los numeros 10, 20, 30, ..., 200. Cree el vector previamente mencionado haciendo uso de la función `seq()`. Guarde e imprimar los resultados de la matriz en una variable/objeto llamada `Matriz_Ejer`.

2. Haciendo uso de la funciones `rownames()` y `colnames()` asígnele a la matriz creada en el ejercicio 1 `Matriz_Ejer` los nombres a las filas y a las columnas. Los nombres de las filas están contenidas en el vector `c('Fila1',	'Fila2',	'Fila3',	'Fila4',	'Fila5')` y los de las columnas en el vector `c('Colum1',	'Colum2',	'Colum3',	'Colum4')`. Imprima los resultados de la matriz `Matriz_Ejer` con los nombres asignados.

3. Adicione a la matriz creada en el ejercicio 2 `Matriz_Ejer`, haciendo uso de la función `rbind()`, una nueva fila con los elementos `c(210, 220, 230, 240)`. Luego, a la matriz resultante con la nueva fila, asígnele una nueva columna con los elementos `c(50, 90, 130, 170, 210, 250)`. La matriz `Matriz_Ejer` ahora cuenta con 6 filas y 5 columnas; no obstante, la fila 6 y la columna 5 no tienen asignado un nombre. ¿Qué debemos hacer para asignarle el nombre `Fila5` a la fila 5 y el nombre `Colum5'` a la columna 5 de la matriz `Matriz_Ejer`.

4. Cree en R una matriz de 4 `filas` y 4 `columnas`, ingrese los datos por columnas a través de un vector construido haciendo uso de la función `rep()` de tal manera que la primera columna esté compuesta por unos (1), la segunda por doses (2), la tercera por treses (3) y la cuarta, por cuatros (4). Ingrese, al crear la anterior matriz y haciendo uso del argumento `dimnames` de la función `matrix()`, los nombres de las filas y las columnas los cuales deben ser, respectivamente, `c('Fil1', 'Fil2', 'Fil3' y 'Fil4')` y `c('Co1', 'Col2', 'Col3' y 'Col4')`. Almacene los resultados en una variable/objeto llamada `Matriz_Rep`.

A partir de la matriz previamente creada `Matriz_Rep`, desarrolle las siguientes actividades.

+ Seleccione la totalidad de elementos de la fila 1.

+ Seleccione la totalidad de elementos de la columna 3.

+ Seleccione el elemento ubicado en la fila 3 columna 4.

+ Seleccione, haciendo uso de vectores con enteros positivos, las columnas 3 y 4.

+ Seleccione, haciendo uso de vectores con elementos lógicos, los elementos ubicados en las filas 2 y 4.

+ Seleccione, a través de una única consulta, los elementos ubicados en las intersecciones de las filas 1 y 3 y las columnas 1 y 4. Para el caso de las filas hacer uso de un vector con enteros negativos y para el caso de las columnas hacer uso de un vector de tipo caracter (textual).

5. El conjunto de datos `mtcars`, al igual que el conjunto de datos `iris` y que se trabajó a lo largo del documento, hace parte de los marcos de datos `data.frame` que vienen incluidos por defecto en R desde el momento de su instalación^[Estos conjuntos de datos hacen parte de una librería llamada `datasets` cuyos conjuntos de datos pueden ser explorados haciendo uso de la función `data()`. De igual manera, estos pueden ser descargados en formatos CSV desde la siguiente [página web](https://vincentarelbundock.github.io/Rdatasets/datasets.html)]. Haciendo uso de las funciones `class()`, `names()`, `dim()`, `length()`, `ncol()`, `nrow()`, `head()`, `tail()`, `str()` y `summary()`, explorar el contenido del marco de datos **`mtcars`**.

6. Selecionar la variable `carb` del conjunto de datos (data.frame) `mtcars` haciendo uso de los operadores `[]`, `[ , ]`, `[[ ]]` y `$`. ¿Existe alguna diferencia en el resultado al usar alguna de estas formas de extracción de una variable en R?

7. Seleccionar las variables `mpg`, `disp`, `drat`, `qsec`, `am` y `carb` del conjunto de datos `mtcars`. El proceso de selección de estas variables debe realizarse a través de cuatro vías: haciendo uso de vectores con _enteros positivos_, haciendo uso de vectores con _enteros negativos_, haciendo uso de vectores con _elementos lógicos_ y haciendo uso de vectores con datos de tipo _caracter o textuales_.

8. Seleccionar, del conjunto de datos `mtcars`, los  individuos con valores 4 o 6 en la variable `cyl` y cuyos valores en la variable `mpg` son mayores o iguales `>=` a 25. Para estos individuos, retener la información de las variables `mpg`, `cyl` y `carb`. Guardar/almacenar e imprimir los resultados de este ejercicio en un objeto/variable llamado `mtcars_new`. 

9. Tomando como referencia el conjunto de datos `mtcars`, realizar las siguientes actividades. Cada uno de los ejercicios **debe** partir del conjunto de datos original; es decir, sin manipulaciones o ajustes previos del marco de datos `mtcars`. Para ello, iniciar el desarrollo de los siguientes ítems limpiando el **Environment** de **Rstudio**.<br>

**Recomendación**. 
*Al inicio de cada uno de los ejercicios cree, a partir del conjunto de datos `mtcars`, el nuevo conjunto de datos con el nombre requerido.  Por ejemplo, para el primero de los ejercicios que se presenta a continuación, se podrá crear el nuevo conjunto de datos haciendo uso de la línea de código `mtcars_name <- mtcars` y sobre este nuevo set de datos realizar el ejercicio requerido. La misma recomendación aplica para el desarrollo de los demás ejercicios del presente numeral. Si presenta problemas en alguno de los ejercicios, limpiar el **Environment** de **Rstudio** y  reiniciar su desarrollo.* 
<br>

+ Cambiar los nombres de las variables  `hp`, `wt` y `am` por los nombres `hp_new`, `wt_new` y `am_new`. Guarde e imprima los resultados con los nuevos nombres de las variables en un objeto llamado `mtcars_name`.

+ Eliminar, haciendo uso de vectores, las variables `drat`, `wt`, `qsec`, `vs`, `am`, `gear` y `carb`. Guardar e imprimir los últimos 5 resultados del nuevo conjunto de datos en un objeto llamado `mtcars_vec`. 

+ Eliminar, haciendo uso del dato `NULL`, las variables `mpg`, `cyl`,  `disp` y   `hp`. Guardar e imprimir los resultados en un objeto `data.frame` llamado `mtcars_nulos`. 

+ Modificar/cambiar por 3.000 el valor de la variable `wt` del individuo ubicado en la posición 1 (fila 1). Guardar e imprimir los resultados de los primeros 5 individuos en un objeto llamado `mtcars_modif`.

+ Eliminar, haciendo uso de vectores, los primeros 5 individuos. Guardar y presentar los primeros 10 resultados en un nuevo conjunto de datos llamado `mtcars_ind2`.

+ Adicionar una nueva variable llamada `New_Var` con los valores 2, 4, 6, 8, ... Guardar e imprimir los primeros 10 individuos en un objeto llamado `mtcars_var_new`.

+ Adicionar un nuevo individuo al conjunto de datos `mtcars`. Seleccione los valores que a bien considere (aleatorios) para las 11 variables que conforman este conjunto de datos y requeridas para adicionar este nuevo individuo. Guardar e imprimir los resultados desde un objeto llamado `mtcars_new_ind`.  


10. Explorar, en la web, la utilidad de la función **`subset()`** de R e indagar si esta puede ser empleada para extraer, del conjunto de datos `iris`, las variables `Sepal.Length`, `Petal.Length` y  `Species` de las flores cuya especie `Species` es igual a `setosa`. Si no es posible realizar la anterior consulta, explicar por qué?
